listening-port=3478
fingerprint
lt-cred-mech
user=hc:hcpassword
realm=human-conversation.local
listening-ip=0.0.0.0
relay-ip=0.0.0.0
min-port=49152
max-port=49200
no-multicast-peers
no-cli
no-tls
no-dtls
verbose
external-ip=172.20.10.3
